### ISSUE TITLE
ConnectedNode missing when using crow.mini.js built with rake

### ISSUE THREAD

**Issue by VincentBlouin** [nanodeath/CrowLib#12]
Hi maybe Im missing something but I did a rake command in the crow folder and I had a crow.mini.js generated in dist. I added the script file in my html. I see GridNode BaseNode and Node when I type crow in my javascript console but I dont see ConnectedNode. How is that ? am I missing something?

Thanks !

**Comment by nanodeath** [comment]
Not missing anything, just not something that I had included in the All.js file.  But it is now, as of 8a5f766a334e9c398c5159e7d43117fe53fdd6dc.  Thanks for reporting!  FYI, with another commit I made at the same time I tweaked the build instructions a bit (and updated the readme) to use Bundler.
